baseurl = "https://taeyeonkim90.github.io" # Hostname (and path) to the root.
title = "andrewkim" # Site title.
theme = "coder" # Set the theme.
languagecode = "en" # The site’s language code.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

[taxonomies]
   tag = "tags"
   category = "categories"

[params] # theme parameters
    author = ">>> import andrew" # Author's name.
    info = "Developer. Educator. Motivator." # Author's job title or info.
    description = "Andrew Kim's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.

    disqusShortname = "" # Enable or disable Disqus

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # RTL support
    rtl = false

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/taeyeonkim90/"
[[params.social]]
    name = "LinkedIn"
    weight = 2
    url = "https://www.linkedin.com/in/andrew-kim-73ba27114/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Categories"
    weight = 2
    url = "/categories/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"